F3 inscription connexion deconnexion
azuera/adopte-un-dog pull request #10
Opened 2023-06-14 14:39 UTC by azuera

creation de la page d'inscription
ajout du login et deconnection dans la nav bar

2023-06-15 12:56 UTC, Eriole requested changes, later dismissed
Mise en forme sur la page inscription
Mise en forme sur la page connexion
Mise en forme sur la page modification
Nom des routes : inscription (au lieu de register), connexion (au lieu de login) etc.

2023-06-15 13:12 UTC, Eriole commented on templates/security/login.html.twig
> +    <h1 class="h3 mb-3 font-weight-normal">Connecte toi allezzzzzz viens!!!!! On est bien!!!!!</h1>
h2 s'il te plait :) je reviendrais pas sur le texte, tu sais ce que j'en pense... bref... a bon entendeur...

2023-06-19 06:36 UTC, Eriole submitted a review, later dismissed
Toujours pas de mise en forme... 😢

2023-06-19 06:36 UTC, Dreeckan submitted a review, later dismissed
Quelques changements de textes à prévoir et un peu de mise en forme serait parfait :P

2023-06-19 13:31 UTC, Eriole approved these changes
A contre coeur.

2023-06-19 13:31 UTC, merged